# redis链接配置
spring:
  redis:
    database: 3
    host: 127.0.0.1 # 按需配置
    port: 6378
    timeout: 10000ms
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 2000
server:
  port: 8000